version: 2.1

executors:
    android:
        docker:
            - image: circleci/android:api-30

jobs:
    build:
        executor: android
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "build.gradle" }}
                      - v1-dependencies-

            - run:
                  name: Download dependencies
                  command: ./gradlew androidDependencies

            - save_cache:
                  paths:
                      - ~/.gradle
                  key: v1-dependencies-{{ checksum "build.gradle" }}

            # Run Fastlane
            - run:
                  name: Run Fastlane
                  command: bundle exec fastlane distribute

            # Save artifacts
            - store_artifacts:
                  path: app/build/outputs/apk/release/app-release.apk

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
