version: 2.1

executors:
    android:
        docker:
            - image: reactnativecommunity/react-native-android:latest

jobs:
    build:
        executor: android
        environment:
            LC_ALL: 'en_US.UTF-8'
            LANG: 'en_US.UTF-8'
            GRADLE_OPTS: '-Xmx2014m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError"'
        steps:
            - checkout

            # Ensure the correct directory
            - run:
                  name: Ensure correct directory
                  command: pwd && ls -la

            # Cache Yarn dependencies
            - run:
                  name: Download and install dependencies
                  command: |
                      sudo apt-get update
                      sudo apt-get install -y curl
                      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                      nvm install 20.11.0
                      nvm use 20.11.0
                      npm install -g yarn
                      yarn install

            - save_cache:
                  paths:
                      - ~/.cache/yarn
                  key: v1-yarn-cache-{{ checksum "yarn.lock" }}

            # Cache Gradle dependencies
            - restore_cache:
                  keys:
                      - v1-gradle-cache-{{ checksum "android/build.gradle" }}
                      - v1-gradle-cache-

            - run:
                  name: List Android directory before secretKey contents
                  command: ls -la
                  working_directory: android

            - run:
                  name: Decrypting Service_account_key
                  command: |
                      base64 -di fbt > fbt.json
                  working_directory: android

            - run:
                  name: List Android directory after secretKey contents
                  command: ls -la
                  working_directory: android

            - run:
                  name: Set permissions for Gradle
                  command: chmod +x ./android/gradlew

            - run:
                  name: Install Fastlane
                  command: bundle install
                  working_directory: android

            - run:
                  name: Update Fastlane
                  command: bundle update fastlane
                  working_directory: android

            - run:
                  name: Clean and Build APK
                  command: |
                      cd android
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                      nvm use 20.11.0
                      chmod +x gradlew
                      ./gradlew clean
                      ./gradlew assembleRelease

            - save_cache:
                  paths:
                      - ~/.gradle
                  key: v1-gradle-cache-{{ checksum "android/build.gradle" }}

            - run:
                  name: Add Firebase App Distribution Plugin
                  command: bundle exec fastlane add_plugin firebase_app_distribution
                  working_directory: android

            - run:
                  name: Deploy to Firebase
                  command: bundle exec fastlane distribute
                  working_directory: android

            # - store_artifacts:
            #       path: android/app/build/outputs/apk/release/app-release.apk
            #       destination: app-release.apk

workflows:
    version: 2
    build:
        jobs:
            - build
