version: 2.1

executors:
    android:
        docker:
            - image: circleci/android:api-30

jobs:
    build:
        executor: android
        steps:
            - checkout

            # Download and cache dependencies for the project-level build.gradle
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "android/build.gradle" }}
                      - v1-dependencies-

            - run:
                  name: Download project-level dependencies
                  command: cd android && ./gradlew androidDependencies

            # Cache dependencies for the app-level build.gradle
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: v1-dependencies-{{ checksum "android/build.gradle" }}

            # Download and cache dependencies for the app-level build.gradle
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "android/app/build.gradle" }}
                      - v1-dependencies-

            - run:
                  name: Download app-level dependencies
                  command: cd android && ./gradlew app:dependencies

            - save_cache:
                  paths:
                      - ~/.gradle
                  key: v1-dependencies-{{ checksum "android/app/build.gradle" }}

            # Run Fastlane
            - run:
                  name: Run Fastlane
                  command: cd android && bundle exec fastlane distribute

            # Save artifacts
            - store_artifacts:
                  path: android/app/build/outputs/apk/release/app-release.apk

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
