version: 2.1

orbs:
    node: circleci/node@5

jobs:
    build:
        docker:
            - image: reactnativecommunity/react-native-android:latest
        environment:
            GRADLE_OPTS: '-Xmx2014m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError"'
        working_directory: ~/repo
        resource_class: 'xlarge'
        steps:
            - checkout

            # Install Node.js and npm
            - run:
                  name: Install Node.js and npm
                  command: |
                      sudo apt-get update
                      sudo apt-get install -y nodejs npm

            # Install Yarn
            - run:
                  name: Install Yarn
                  command: sudo npm install -g yarn

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run:
                  name: Install dependencies
                  command: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # Set up the JDK
            - run:
                  name: Set up JDK
                  command: |
                      sudo apt-get update
                      sudo apt-get install -y openjdk-8-jdk
                      sudo update-alternatives --config java

            # Set up Gradle
            - restore_cache:
                  keys:
                      - gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
                      - gradle-

            - run:
                  name: Assemble Release
                  command: ./gradlew assembleRelease

            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

            # Store the APK as a CircleCI artifact
            - store_artifacts:
                  path: android/app/build/outputs/apk/release
                  destination: apk

workflows:
    version: 2
    build:
        jobs:
            - build
