version: 2.1

orbs:
    node: circleci/node@5

jobs:
    build:
        docker:
            - image: reactnativecommunity/react-native-android:latest
        environment:
            GRADLE_OPTS: '-Xmx2014m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError"'
        working_directory: ~/repo
        steps:
            - checkout

            # Install Node.js and npm
            - run:
                  name: Install Node.js and npm
                  command: |
                      sudo apt-get update
                      sudo apt-get install -y nodejs npm

            # Install Yarn
            - run:
                  name: Install Yarn
                  command: sudo npm install -g yarn

            - run:
                  name: Chmod permissions
                  command: sudo chmod +x ./gradlew
                  working_directory: android

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run:
                  name: Install dependencies
                  command: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # Set up the JDK
            - run:
                  name: Set up JDK
                  command: |
                      sudo apt-get update

            # Set up Gradle
            - restore_cache:
                  keys:
                      - v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}

            - save_cache:
                  paths:
                      - ~/.gradle
                  key: v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}

            # Store the APK as a CircleCI artifact
            # - store_artifacts:
            #     path: android/app/build/outputs/apk/release
            #     destination: apk

    deploy_firebase:
        docker:
            - image: cimg/ruby:3.0.0
        environment:
            # Set JAVA_HOME to the correct path based on the Docker image used
            JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        working_directory: android
        steps:
            - checkout

            # Debugging step to list the contents of the android directory
            - run:
                  name: List android directory contents
                  command: ls -la android

            # Debugging step to list the contents of the fastlane directory
            - run:
                  name: List fastlane directory contents
                  command: ls -la android/fastlane

            - run:
                  name: Chmod permissions
                  command: sudo chmod +x ./gradlew
                  working_directory: android

            # Install Fastlane
            - run:
                  name: Install Fastlane
                  command: bundle install
                  working_directory: android

            # Run Fastlane to deploy to Firebase
            - run:
                  name: Deploy to Firebase
                  command: bundle exec fastlane distribute
                  working_directory: android

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy_firebase:
                  requires:
                      - build
