# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute app to Firebase App Distribution"
  lane :distribute do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    firebase_app_distribution(
      groups: "mytesters",
      release_notes: "Automated release notes for this build.",
      android_artifact_type:"APK",
      android_artifact_path: "./app/build/outputs/apk/release/app-release.apk",
      service_credentials_file: "fbt.json",
      app: "1:940585881554:android:06a0d1c7163d3866af820b",
      debug:true
    )
  end
end
