# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute app to Firebase App Distribution"
  lane :distribute_to_firebase do
    # gradle(
    #   task: "assemble",
    #   build_type: "Release"
    # )
    File.open("fbt.json", "w") do |file|
      file.write(Base64.decode64(ENV["GOOGLE_APPLICATION_CREDENTIALS_JSON"]))
    end

    ENV["GOOGLE_APPLICATION_CREDENTIALS"] = "fbt.json"


    firebase_app_distribution(
      app: "1:940585881554:android:06a0d1c7163d3866af820b", # Replace with your Firebase App ID
      groups: "your_tester_group", # Replace with your tester group
      release_notes: "Automated release notes for this build.",
      # firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
